matrix:
  include:
    - name: "Build C++/Java and Upload to S3 on AL2012"
      os: linux
      services: docker
      dist: focal
      before_install:
        - echo "################################################################################"
        - echo "Installing Dependencies for Linux/x86_64"
        - echo "################################################################################"
        - sudo apt-get update
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
        - unzip awscliv2.zip
        - sudo ./aws/install
        - export PATH=~/bin:$PATH
        - mkdir -p ~/.aws
        - |
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
        - cat <<'EOF' >> ~/.aws/credentials
        - echo "################################################################################"
        - echo "SUCCESS Installed Dependencies for Linux/x86_64"
        - echo "################################################################################"
      script:
        - echo "################################################################################"
        - echo "Starting build phase for Linux/x86_64"
        - echo "################################################################################"
        - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 056543101242.dkr.ecr.us-west-2.amazonaws.com
        - echo "Getting Docker image for AL2012 build of KPL..."
        - docker pull 056543101242.dkr.ecr.us-west-2.amazonaws.com/kinesis-producer-library-builder:latest
        - ls
        - df -h
        - echo "Building KPL in current directory in the Container..."
        - docker run --memory 9g -v $(pwd):/kpl -it 056543101242.dkr.ecr.us-west-2.amazonaws.com/kinesis-producer-library-builder:latest /bin/bash -c "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY && export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID && cd /kpl && ls && ./bootstrap.sh"
        - cd java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/$TRAVIS_OS_NAME-`uname -m`
        - ls
        - sudo zip kinesis-producer.zip kinesis_producer
        - echo "Uploading build artifacts for KPL built on Linux..."
        - aws s3 cp kinesis-producer.zip s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/$TRAVIS_OS_NAME-`uname -m`/kinesis-producer.zip
        - echo "################################################################################"
        - echo "SUCCESS Build phase for Linux/x86_64, complete. Check for any errors reported"
        - echo "################################################################################"
    - name: "Build C++/Java and Upload to S3 on AL2/Arm64"
      os: linux
      arch: arm64-graviton2
      virt: vm
      services: docker
      dist: focal
      group: edge
      before_install:
        - echo "################################################################################"
        - echo "Installing Dependencies for Linux/arm64"
        - echo "################################################################################"
        - sudo apt-get update
        - sudo apt-get install python3
        - sudo apt-get -y install python3-pip
        - pip3 --version
        - pip3 install --user awscli
        - mkdir -p ~/.aws
        - |
          cat > ~/.aws/credentials << EOF
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
        - cat <<'EOF' >> ~/.aws/credentials
        - echo "################################################################################"
        - echo "SUCCESS Installed Dependencies for Linux/arm64"
        - echo "################################################################################"
      script:
        - echo "################################################################################"
        - echo "Starting build phase for Linux/arm64"
        - echo "################################################################################"
        - $(aws ecr get-login --no-include-email --region us-west-2)
        - echo "Getting Docker image for AL2/Arm64 build of KPL..."
        - docker pull amazonlinux:2
        - ls
        - df -h
        - echo "Building KPL in current directory in the Container..."
        - docker run --memory 9g -v $(pwd):/kpl -it amazonlinux:2 /bin/bash -c "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY && export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID && yum install -y -q cmake3 gcc gcc-c++ make file tar gzip which perl git libuuid libuuid-devel maven zlib zlib-devel zlib-static && cd /kpl && ls && ./bootstrap.sh"
        - cd java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/$TRAVIS_OS_NAME-`uname -m`
        - ls
        - sudo zip kinesis-producer.zip kinesis_producer
        - echo "Uploading build artifacts for KPL built on Linux Arm64..."
        - aws s3 cp kinesis-producer.zip s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/$TRAVIS_OS_NAME-`uname -m`/kinesis-producer.zip
        - echo "################################################################################"
        - echo "SUCCESS Build phase for Linux/arm64, complete. Check for any errors reported"
        - echo "################################################################################"
    - name: "Build C++/Java and Upload to S3 on OSX"
      os: osx
      compiler: clang
      osx_image: xcode13.1
      script:
       - curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
       - sudo installer -pkg AWSCLIV2.pkg -target /
       - java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home'
       - export JAVA_HOME=$(java -XshowSettings:properties -version 2>&1 > /dev/null | grep 'java.home' | awk '{print $3}')
       - DIR=$(pwd)
       - ./bootstrap.sh
       - cd java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/$TRAVIS_OS_NAME
       - zip kinesis-producer.zip kinesis_producer
       - aws s3 cp kinesis-producer.zip s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/$TRAVIS_OS_NAME/kinesis-producer.zip
       - echo "################################################################################"
       - echo "Finished building KPL on OSX...Starting Bundling of Linux/x86_64 with OSX binaries"
       - echo "################################################################################"
       - test -e $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/osx/kinesis_producer
       - aws s3 cp s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/linux-x86_64/kinesis-producer.zip linux-x86_64-binaries.zip
       - mkdir -p java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-x86_64/
       - unzip linux-x86_64-binaries.zip -d $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-x86_64/
       - cd $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-x86_64/
       - pwd
       - ls
       - test -e $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-x86_64/kinesis_producer
       - cd $DIR
       - pwd
       - ls
       - echo "################################################################################"
       - echo "Starting Bundling of Linux/arm64 with OSX binaries"
       - echo "################################################################################"
       - aws s3 cp s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/linux-aarch64/kinesis-producer.zip linux-aarch64-binaries.zip
       - mkdir -p java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-aarch64/
       - unzip linux-aarch64-binaries.zip -d $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-aarch64/
       - cd $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-aarch64/
       - pwd
       - ls
       - test -e $DIR/java/amazon-kinesis-producer/src/main/resources/amazon-kinesis-producer-native-binaries/linux-aarch64/kinesis_producer
       - cd $DIR
       - pwd
       - ls
       - echo "################################################################################"
       - echo "Starting the build phase for amazon-kinesis-producer and amazon-kinesis-producer-sample $KPL_VERSION"
       - echo "################################################################################"
       - cd $DIR/java/amazon-kinesis-producer/
       - pwd
       - ls
       - mvn clean package source:jar javadoc:jar install
       - cd $DIR
       - pwd
       - ls
       - cd $DIR/java/amazon-kinesis-producer-sample/
       - mvn clean package
       - cd $DIR
       - pwd
       - ls
       - cd $DIR/java/amazon-kinesis-producer/target
       - pwd
       - ls
       - zip -R amazon-kinesis-producer-jars.zip '*.jar'
       - aws s3 cp $DIR/java/amazon-kinesis-producer/target/amazon-kinesis-producer-jars.zip  s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/release/amazon-kinesis-producer-jars.zip
       - cd $DIR
       - pwd
       - ls
       - cd $DIR/java/amazon-kinesis-producer-sample/target
       - pwd
       - ls
       - aws s3 cp $DIR/java/amazon-kinesis-producer-sample/target/amazon-kinesis-producer-sample-1.0.0.jar  s3://kpl-build-kinesis-internal/$KPL_VERSION-$HASH/release/amazon-kinesis-producer-sample-1.0.0.jar
       - cd $DIR
       - pwd
       - ls
       - echo "################################################################################"
       - echo "SUCCESS, Uploaded Zipped Release Artifacts"
       - echo "################################################################################"
before_script:
 - cd java/amazon-kinesis-producer
 - HASH=$(git rev-parse HEAD)
 - KPL_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
 - echo "Found KPL version $KPL_VERSION in current directory $PWD ... "
 - echo "Starting Packaging of KPL.$KPL_VERSION"
 - cd ../..
after_success:
  - sleep 10
after_failure:
  - sleep 10
